// Mocks generated by Mockito 5.4.5 from annotations
// in data/test/data/repository/landmark_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:data/data.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutoDisposeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.AutoDisposeNotifierProviderRef<T> {
  _FakeAutoDisposeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LandmarkListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockLandmarkListNotifier extends _i1.Mock
    implements _i3.LandmarkListNotifier {
  MockLandmarkListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AutoDisposeNotifierProviderRef<List<_i3.Landmark>> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeAutoDisposeNotifierProviderRef_0<List<_i3.Landmark>>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.AutoDisposeNotifierProviderRef<List<_i3.Landmark>>);

  @override
  List<_i3.Landmark> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: <_i3.Landmark>[],
      ) as List<_i3.Landmark>);

  @override
  set state(List<_i3.Landmark>? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i3.Landmark> build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: <_i3.Landmark>[],
      ) as List<_i3.Landmark>);

  @override
  void setLandmarkList(List<_i3.Landmark>? landmarkList) => super.noSuchMethod(
        Invocation.method(
          #setLandmarkList,
          [landmarkList],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFavorite(
    int? id,
    bool? isFavorite,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setFavorite,
          [
            id,
            isFavorite,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      List<_i3.Landmark>?,
      List<_i3.Landmark>,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    List<_i3.Landmark>? previous,
    List<_i3.Landmark>? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
      ) as bool);
}
