name: ga913_flutter

packages:
  - apps/**
  - packages/**

scripts:
  format:
    exec: dart format --set-exit-if-changed .
  custom_lint:
    exec: dart run custom_lint
  analyze:
    run: flutter analyze
    exec:
      concurrency: 1
  test:
    run: flutter test
    exec:
      concurrency: 1
  codegen:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner

command:
  bootstrap:
    environment:
      sdk: ^3.6.0
      flutter: ^3.27.1
    dependencies:
      flutter:
        sdk: flutter
      cupertino_icons: ^1.0.8
      freezed_annotation: ^3.0.0
      hooks_riverpod: ^2.6.1
      flutter_hooks: ^0.20.5
      riverpod_annotation: ^2.6.1
      flutter_localizations:
        sdk: flutter
      intl: ^0.19.0
      auto_route: ^9.2.2
      json_annotation: ^4.9.0

    dev_dependencies:
      flutter_test:
        sdk: flutter
      flutter_lints: ^4.0.0
      freezed: ^3.0.6
      build_runner: ^2.4.13
      riverpod_generator: ^2.6.1
      custom_lint: ^0.7.5
      riverpod_lint: ^2.6.2
      mockito: ^5.4.4
      auto_route_generator: ^9.0.0
      json_serializable: ^6.8.0

ide:
  intellij:
    enabled: false
