name: ga913_flutter
description: "Flutter learning project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: 2.5.7
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.1
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
