name: check
on:
  # mainブランチへのPUSH
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true
      - run: dart pub global activate melos
      - run: melos bootstrap
      - run: melos run format
      - run: melos run custom_lint
      - run: melos run analyze
      - run: melos run test
